### ISSUE TITLE
Please add translation in English for README. And CMake's qt-plugins did not exist.

### ISSUE THREAD

**Issue by gusbemacbe** [roachsinai/krunner-linuxcommands#1]
Hello @roachsinai !

I would like to use your plugin for running aliases with Krunner. But as README is written in Chinese, I do not know how I install.

**Comment by gusbemacbe** [comment]
Hello, there is another error:

```zsh
cmake .. -DCMAKE_INSTALL_PREFIX=`kf5-config --prefix` -DQT_PLUGIN_INSTALL_DIR=`kf5-config --qt-plugins`
CMake Error: The source directory "/home/gusbemacbe/GitHub/krunner-linuxcommands/build/--qt-plugins`" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by gusbemacbe** [comment]
It seems that the error has been solved witht he correction of `cmake .. -DCMAKE_INSTALL_PREFIX='kf5-config --prefix' -DQT_PLUGIN_INSTALL_DIR='kf5-config --qt5-plugins'`.

**Comment by gusbemacbe** [comment]
The `data,json` does nor exist.

**Comment by roachsinai** [comment]
Hi @gusbemacbe I have no KDE on my PC right now.

What you need do to install this plugin is:

1. `wget https://raw.githubusercontent.com/jaywcjlove/linux-command/master/dist/data.json ~/.data.json`
2. run install.sh directly in your clone directory

And if you don't need it run `uninstall.sh` directly, too.

**Comment by roachsinai** [comment]
What this plugin do is open a web page which shows the Chinese explanation of the command people want.

For example when you input `lc` in Krunner, this plugin triggered. Then if you input a command like `ls`, then press <kbd>Enter</kbd>, this plugin will open a Chinese explanation version of `ls` webpage.

As above this plugin works only for people who wanna read a Chinese version command manual, so I think the English version README.md is not suitable.

**Comment by roachsinai** [comment]
> Hi @gusbemacbe I have no KDE on my PC right now.
> 
> What you need do to install this plugin is:
> 
> 1. `wget https://raw.githubusercontent.com/jaywcjlove/linux-command/master/dist/data.json ~/.data.json`
> 2. run install.sh directly in your clone directory
> 
> And if you don't need it run `uninstall.sh` directly, too.

Wish above quote could help you install this plugin.

**Comment by gusbemacbe** [comment]
I wanted to install manually with the latest version of QT, but you suggested me to use `install.sh`, so I did, it worked. I understood what happened with the `data.json`. My fish shell does not support it. I downloaded and moved the file. It worked. 

Sorry for my inconvenience.
